coor <- c(0,0)
trellis.par.set("axis.line",list(col=NA,lty=1,lwd=1)) 
Graph <- xyplot(c(0)~c(0), xlab="", ylab="", type="l", 
                scales=list(draw=FALSE),subscripts = TRUE) 
Graph + layer({panel.text(coor[1], coor[2], "-O-") })
n_coor <- as.data.frame(matrix(round(runif(2*n) / 5, digits=3), nrow = n) )

n_coor[1,] <- c(0,0)



Graph <- Graph + layer(panel.lines( x = c(n_coor[ 1 ,1], n_coor[ 2 ,1]), y = c(n_coor[ 1 ,2], n_coor[ 2 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 2 ,1], y=n_coor[ 2 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 2 ,1], n_coor[ 3 ,1]), y = c(n_coor[ 2 ,2], n_coor[ 3 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 3 ,1], y=n_coor[ 3 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 3 ,1], n_coor[ 4 ,1]), y = c(n_coor[ 3 ,2], n_coor[ 4 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 4 ,1], y=n_coor[ 4 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 4 ,1], n_coor[ 5 ,1]), y = c(n_coor[ 4 ,2], n_coor[ 5 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 5 ,1], y=n_coor[ 5 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 5 ,1], n_coor[ 6 ,1]), y = c(n_coor[ 5 ,2], n_coor[ 6 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 6 ,1], y=n_coor[ 6 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 6 ,1], n_coor[ 7 ,1]), y = c(n_coor[ 6 ,2], n_coor[ 7 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 7 ,1], y=n_coor[ 7 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 7 ,1], n_coor[ 8 ,1]), y = c(n_coor[ 7 ,2], n_coor[ 8 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 8 ,1], y=n_coor[ 8 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 8 ,1], n_coor[ 9 ,1]), y = c(n_coor[ 8 ,2], n_coor[ 9 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 9 ,1], y=n_coor[ 9 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 9 ,1], n_coor[ 10 ,1]), y = c(n_coor[ 9 ,2], n_coor[ 10 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 10 ,1], y=n_coor[ 10 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 10 ,1], n_coor[ 11 ,1]), y = c(n_coor[ 10 ,2], n_coor[ 11 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 11 ,1], y=n_coor[ 11 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 11 ,1], n_coor[ 12 ,1]), y = c(n_coor[ 11 ,2], n_coor[ 12 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 12 ,1], y=n_coor[ 12 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 12 ,1], n_coor[ 13 ,1]), y = c(n_coor[ 12 ,2], n_coor[ 13 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 13 ,1], y=n_coor[ 13 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 13 ,1], n_coor[ 14 ,1]), y = c(n_coor[ 13 ,2], n_coor[ 14 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 14 ,1], y=n_coor[ 14 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 14 ,1], n_coor[ 15 ,1]), y = c(n_coor[ 14 ,2], n_coor[ 15 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 15 ,1], y=n_coor[ 15 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 15 ,1], n_coor[ 16 ,1]), y = c(n_coor[ 15 ,2], n_coor[ 16 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 16 ,1], y=n_coor[ 16 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 16 ,1], n_coor[ 17 ,1]), y = c(n_coor[ 16 ,2], n_coor[ 17 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 17 ,1], y=n_coor[ 17 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 17 ,1], n_coor[ 18 ,1]), y = c(n_coor[ 17 ,2], n_coor[ 18 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 18 ,1], y=n_coor[ 18 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 18 ,1], n_coor[ 19 ,1]), y = c(n_coor[ 18 ,2], n_coor[ 19 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 19 ,1], y=n_coor[ 19 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 19 ,1], n_coor[ 20 ,1]), y = c(n_coor[ 19 ,2], n_coor[ 20 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 20 ,1], y=n_coor[ 20 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 20 ,1], n_coor[ 21 ,1]), y = c(n_coor[ 20 ,2], n_coor[ 21 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 21 ,1], y=n_coor[ 21 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 21 ,1], n_coor[ 22 ,1]), y = c(n_coor[ 21 ,2], n_coor[ 22 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 22 ,1], y=n_coor[ 22 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 22 ,1], n_coor[ 23 ,1]), y = c(n_coor[ 22 ,2], n_coor[ 23 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 23 ,1], y=n_coor[ 23 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 23 ,1], n_coor[ 24 ,1]), y = c(n_coor[ 23 ,2], n_coor[ 24 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 24 ,1], y=n_coor[ 24 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 24 ,1], n_coor[ 25 ,1]), y = c(n_coor[ 24 ,2], n_coor[ 25 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 25 ,1], y=n_coor[ 25 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 25 ,1], n_coor[ 26 ,1]), y = c(n_coor[ 25 ,2], n_coor[ 26 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 26 ,1], y=n_coor[ 26 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 26 ,1], n_coor[ 27 ,1]), y = c(n_coor[ 26 ,2], n_coor[ 27 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 27 ,1], y=n_coor[ 27 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 27 ,1], n_coor[ 28 ,1]), y = c(n_coor[ 27 ,2], n_coor[ 28 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 28 ,1], y=n_coor[ 28 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 28 ,1], n_coor[ 29 ,1]), y = c(n_coor[ 28 ,2], n_coor[ 29 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 29 ,1], y=n_coor[ 29 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 29 ,1], n_coor[ 30 ,1]), y = c(n_coor[ 29 ,2], n_coor[ 30 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 30 ,1], y=n_coor[ 30 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 30 ,1], n_coor[ 31 ,1]), y = c(n_coor[ 30 ,2], n_coor[ 31 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 31 ,1], y=n_coor[ 31 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 31 ,1], n_coor[ 32 ,1]), y = c(n_coor[ 31 ,2], n_coor[ 32 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 32 ,1], y=n_coor[ 32 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 32 ,1], n_coor[ 33 ,1]), y = c(n_coor[ 32 ,2], n_coor[ 33 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 33 ,1], y=n_coor[ 33 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 33 ,1], n_coor[ 34 ,1]), y = c(n_coor[ 33 ,2], n_coor[ 34 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 34 ,1], y=n_coor[ 34 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 34 ,1], n_coor[ 35 ,1]), y = c(n_coor[ 34 ,2], n_coor[ 35 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 35 ,1], y=n_coor[ 35 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 35 ,1], n_coor[ 36 ,1]), y = c(n_coor[ 35 ,2], n_coor[ 36 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 36 ,1], y=n_coor[ 36 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 36 ,1], n_coor[ 37 ,1]), y = c(n_coor[ 36 ,2], n_coor[ 37 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 37 ,1], y=n_coor[ 37 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 37 ,1], n_coor[ 38 ,1]), y = c(n_coor[ 37 ,2], n_coor[ 38 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 38 ,1], y=n_coor[ 38 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 38 ,1], n_coor[ 39 ,1]), y = c(n_coor[ 38 ,2], n_coor[ 39 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 39 ,1], y=n_coor[ 39 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 39 ,1], n_coor[ 40 ,1]), y = c(n_coor[ 39 ,2], n_coor[ 40 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 40 ,1], y=n_coor[ 40 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 40 ,1], n_coor[ 41 ,1]), y = c(n_coor[ 40 ,2], n_coor[ 41 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 41 ,1], y=n_coor[ 41 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 41 ,1], n_coor[ 42 ,1]), y = c(n_coor[ 41 ,2], n_coor[ 42 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 42 ,1], y=n_coor[ 42 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 42 ,1], n_coor[ 43 ,1]), y = c(n_coor[ 42 ,2], n_coor[ 43 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 43 ,1], y=n_coor[ 43 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 43 ,1], n_coor[ 44 ,1]), y = c(n_coor[ 43 ,2], n_coor[ 44 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 44 ,1], y=n_coor[ 44 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 44 ,1], n_coor[ 45 ,1]), y = c(n_coor[ 44 ,2], n_coor[ 45 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 45 ,1], y=n_coor[ 45 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 45 ,1], n_coor[ 46 ,1]), y = c(n_coor[ 45 ,2], n_coor[ 46 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 46 ,1], y=n_coor[ 46 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 46 ,1], n_coor[ 47 ,1]), y = c(n_coor[ 46 ,2], n_coor[ 47 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 47 ,1], y=n_coor[ 47 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 47 ,1], n_coor[ 48 ,1]), y = c(n_coor[ 47 ,2], n_coor[ 48 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 48 ,1], y=n_coor[ 48 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 48 ,1], n_coor[ 49 ,1]), y = c(n_coor[ 48 ,2], n_coor[ 49 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 49 ,1], y=n_coor[ 49 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 49 ,1], n_coor[ 50 ,1]), y = c(n_coor[ 49 ,2], n_coor[ 50 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 50 ,1], y=n_coor[ 50 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 50 ,1], n_coor[ 51 ,1]), y = c(n_coor[ 50 ,2], n_coor[ 51 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 51 ,1], y=n_coor[ 51 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 51 ,1], n_coor[ 52 ,1]), y = c(n_coor[ 51 ,2], n_coor[ 52 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 52 ,1], y=n_coor[ 52 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 52 ,1], n_coor[ 53 ,1]), y = c(n_coor[ 52 ,2], n_coor[ 53 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 53 ,1], y=n_coor[ 53 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 53 ,1], n_coor[ 54 ,1]), y = c(n_coor[ 53 ,2], n_coor[ 54 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 54 ,1], y=n_coor[ 54 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 54 ,1], n_coor[ 55 ,1]), y = c(n_coor[ 54 ,2], n_coor[ 55 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 55 ,1], y=n_coor[ 55 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 55 ,1], n_coor[ 56 ,1]), y = c(n_coor[ 55 ,2], n_coor[ 56 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 56 ,1], y=n_coor[ 56 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 56 ,1], n_coor[ 57 ,1]), y = c(n_coor[ 56 ,2], n_coor[ 57 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 57 ,1], y=n_coor[ 57 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 57 ,1], n_coor[ 58 ,1]), y = c(n_coor[ 57 ,2], n_coor[ 58 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 58 ,1], y=n_coor[ 58 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 58 ,1], n_coor[ 59 ,1]), y = c(n_coor[ 58 ,2], n_coor[ 59 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 59 ,1], y=n_coor[ 59 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 59 ,1], n_coor[ 60 ,1]), y = c(n_coor[ 59 ,2], n_coor[ 60 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 60 ,1], y=n_coor[ 60 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 60 ,1], n_coor[ 61 ,1]), y = c(n_coor[ 60 ,2], n_coor[ 61 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 61 ,1], y=n_coor[ 61 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 61 ,1], n_coor[ 62 ,1]), y = c(n_coor[ 61 ,2], n_coor[ 62 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 62 ,1], y=n_coor[ 62 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 62 ,1], n_coor[ 63 ,1]), y = c(n_coor[ 62 ,2], n_coor[ 63 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 63 ,1], y=n_coor[ 63 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 63 ,1], n_coor[ 64 ,1]), y = c(n_coor[ 63 ,2], n_coor[ 64 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 64 ,1], y=n_coor[ 64 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 64 ,1], n_coor[ 65 ,1]), y = c(n_coor[ 64 ,2], n_coor[ 65 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 65 ,1], y=n_coor[ 65 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 65 ,1], n_coor[ 66 ,1]), y = c(n_coor[ 65 ,2], n_coor[ 66 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 66 ,1], y=n_coor[ 66 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 66 ,1], n_coor[ 67 ,1]), y = c(n_coor[ 66 ,2], n_coor[ 67 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 67 ,1], y=n_coor[ 67 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 67 ,1], n_coor[ 68 ,1]), y = c(n_coor[ 67 ,2], n_coor[ 68 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 68 ,1], y=n_coor[ 68 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 68 ,1], n_coor[ 69 ,1]), y = c(n_coor[ 68 ,2], n_coor[ 69 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 69 ,1], y=n_coor[ 69 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 69 ,1], n_coor[ 70 ,1]), y = c(n_coor[ 69 ,2], n_coor[ 70 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 70 ,1], y=n_coor[ 70 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 70 ,1], n_coor[ 71 ,1]), y = c(n_coor[ 70 ,2], n_coor[ 71 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 71 ,1], y=n_coor[ 71 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 71 ,1], n_coor[ 72 ,1]), y = c(n_coor[ 71 ,2], n_coor[ 72 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 72 ,1], y=n_coor[ 72 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 72 ,1], n_coor[ 73 ,1]), y = c(n_coor[ 72 ,2], n_coor[ 73 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 73 ,1], y=n_coor[ 73 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 73 ,1], n_coor[ 74 ,1]), y = c(n_coor[ 73 ,2], n_coor[ 74 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 74 ,1], y=n_coor[ 74 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 74 ,1], n_coor[ 75 ,1]), y = c(n_coor[ 74 ,2], n_coor[ 75 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 75 ,1], y=n_coor[ 75 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 75 ,1], n_coor[ 76 ,1]), y = c(n_coor[ 75 ,2], n_coor[ 76 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 76 ,1], y=n_coor[ 76 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 76 ,1], n_coor[ 77 ,1]), y = c(n_coor[ 76 ,2], n_coor[ 77 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 77 ,1], y=n_coor[ 77 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 77 ,1], n_coor[ 78 ,1]), y = c(n_coor[ 77 ,2], n_coor[ 78 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 78 ,1], y=n_coor[ 78 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 78 ,1], n_coor[ 79 ,1]), y = c(n_coor[ 78 ,2], n_coor[ 79 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 79 ,1], y=n_coor[ 79 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 79 ,1], n_coor[ 80 ,1]), y = c(n_coor[ 79 ,2], n_coor[ 80 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 80 ,1], y=n_coor[ 80 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 80 ,1], n_coor[ 81 ,1]), y = c(n_coor[ 80 ,2], n_coor[ 81 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 81 ,1], y=n_coor[ 81 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 81 ,1], n_coor[ 82 ,1]), y = c(n_coor[ 81 ,2], n_coor[ 82 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 82 ,1], y=n_coor[ 82 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 82 ,1], n_coor[ 83 ,1]), y = c(n_coor[ 82 ,2], n_coor[ 83 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 83 ,1], y=n_coor[ 83 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 83 ,1], n_coor[ 84 ,1]), y = c(n_coor[ 83 ,2], n_coor[ 84 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 84 ,1], y=n_coor[ 84 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 84 ,1], n_coor[ 85 ,1]), y = c(n_coor[ 84 ,2], n_coor[ 85 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 85 ,1], y=n_coor[ 85 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 85 ,1], n_coor[ 86 ,1]), y = c(n_coor[ 85 ,2], n_coor[ 86 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 86 ,1], y=n_coor[ 86 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 86 ,1], n_coor[ 87 ,1]), y = c(n_coor[ 86 ,2], n_coor[ 87 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 87 ,1], y=n_coor[ 87 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 87 ,1], n_coor[ 88 ,1]), y = c(n_coor[ 87 ,2], n_coor[ 88 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 88 ,1], y=n_coor[ 88 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 88 ,1], n_coor[ 89 ,1]), y = c(n_coor[ 88 ,2], n_coor[ 89 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 89 ,1], y=n_coor[ 89 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 89 ,1], n_coor[ 90 ,1]), y = c(n_coor[ 89 ,2], n_coor[ 90 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 90 ,1], y=n_coor[ 90 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 90 ,1], n_coor[ 91 ,1]), y = c(n_coor[ 90 ,2], n_coor[ 91 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 91 ,1], y=n_coor[ 91 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 91 ,1], n_coor[ 92 ,1]), y = c(n_coor[ 91 ,2], n_coor[ 92 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 92 ,1], y=n_coor[ 92 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 92 ,1], n_coor[ 93 ,1]), y = c(n_coor[ 92 ,2], n_coor[ 93 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 93 ,1], y=n_coor[ 93 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 93 ,1], n_coor[ 94 ,1]), y = c(n_coor[ 93 ,2], n_coor[ 94 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 94 ,1], y=n_coor[ 94 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 94 ,1], n_coor[ 95 ,1]), y = c(n_coor[ 94 ,2], n_coor[ 95 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 95 ,1], y=n_coor[ 95 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 95 ,1], n_coor[ 96 ,1]), y = c(n_coor[ 95 ,2], n_coor[ 96 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 96 ,1], y=n_coor[ 96 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 96 ,1], n_coor[ 97 ,1]), y = c(n_coor[ 96 ,2], n_coor[ 97 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 97 ,1], y=n_coor[ 97 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 97 ,1], n_coor[ 98 ,1]), y = c(n_coor[ 97 ,2], n_coor[ 98 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 98 ,1], y=n_coor[ 98 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 98 ,1], n_coor[ 99 ,1]), y = c(n_coor[ 98 ,2], n_coor[ 99 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 99 ,1], y=n_coor[ 99 ,2], "-O-"))) 
Graph <- Graph + layer(panel.lines( x = c(n_coor[ 99 ,1], n_coor[ 100 ,1]), y = c(n_coor[ 99 ,2], n_coor[ 100 ,2]))) 
print(Graph) 
print(Graph + layer(panel.text(x=n_coor[ 100 ,1], y=n_coor[ 100 ,2], "-O-"))) 
