## THIS IS ONLY MAIN IDEA HOW OUR PACKAGE COULD WORK
## I WAS TESTING ADDING AND REMOVING LAYERS ON OBJECTS OF CLASS TRELLIS
## THAT ARE PRODUCED BY PCKG LATTICE.

## LAYERS ARE CREATED BY FUNCTIONS FROM PCKG latticeEXTRA

#Value

# a layer object is defined as a list of expression objects, 
# each of which may have a set of attributes. The result of 
# "adding" a layer to a trellis object (+.trellis) is the 
# updated trellis object.

# Really... ?


?layer
library(latticeExtra)


# turning default external box off
trellis.par.set("axis.line",list(col=NA,lty=1,lwd=1)) 

#You can restore the earlier behavior with: 
   
#trellis.par.set("axis.line",list(col="black",lty=1,lwd=1))


# Preparing an object of class trellis

Graph <- xyplot(0~0, xlab="", ylab="", type="l", 
              scales=list(draw=FALSE)) 
Graph
# Preparin coordinates of a turtle
coor <- c(0,0)
Graph + layer({panel.text(coor[1], coor[2], "-O-") })

# Graph is still a plot withouth a turtle
Graph

# new coordinates to move up to, generated by e.g. move_forward function
n_coor <- c(0.3,0.22)

## adding next line to a plot
Graph + layer(panel.xyplot(y = c(coor[2],n_coor[2]), x=c(coor[1],n_coor[1]),
                   type = "l", col="red"))
## updating our Graph
Graph <- Graph + layer(panel.xyplot(y = c(coor[2],n_coor[2]), x=c(coor[1],n_coor[1]),
                                       type = "l", col="red"))
## checking how does it look like
Graph

## adding turtle to a plot
Graph + layer(panel.text(x=n_coor[1], y=n_coor[2], "-O-"))


## viewing Graph withouth a turtle:
Graph

## after that, we need to substitue coordinates, so we can add a turtle
coor <- n_coor
coor


###########################################
###########################################
################# TEST ####################
###########################################
###########################################


##########################################
# Thats why testing a trellis plot in a loop
# like mine, does not work as we assume it
# should. Quick brief.
###########################################
foo <- xyplot(ozone ~ wind, environmental)
foo


foo <- foo + layer(panel.abline(h = 3))
foo <- foo + layer(panel.lines( x = c(1,20), y = c(3,40), col = "red" ))
foo <- foo + layer(panel.lines( x = c(17,40), y = c(36,71), col = "yellow"))
foo <- foo + layer(panel.lines( x = c(20,4), y = c(36,71), col = "yellow"))

foo <- foo + layer(panel.lines( x = c(7,40), y = c(36,71), col = "green"))
foo <- foo + layer(panel.lines( x = c(7,40), y = c(11,71), col = sample(8,1)))
foo <- foo + layer(panel.text(x=4, y=70, "napis"))
foo <- foo + layer(panel.lines( x = c(7,20), y = c(1,101), col = sample(8,1)))
foo <- foo + layer(panel.lines( x = c(20,40), y = c(101,71), col = sample(8,1)))

# try to run next line a couple of times, to get the wiev of a problem in putting
# trellis object into a loop
foo

#########################################


#########################################
# Real test - 19 seconds - still slower,
# than the rest of ideas.
#########################################



# It might look very primitive, but those are only tests
# Cr8ing a new file.
for (i in 2:n){
   cat("Graph <- Graph + layer(panel.lines( x = c(n_coor[",i-1,",1], n_coor[",i,",1]), y = c(n_coor[",i-1,",2], n_coor[",i,",2]))) \n")
   cat("print(Graph) \n")
   cat("print(Graph + layer(panel.text(x=n_coor[",i,",1], y=n_coor[",i,",2], \"-O-\"))) \n")
}





x <- system.time(expr = {

source("D:/TurboTurtle/devel/Marcin/100_Graphs_in_lattice.R")
})
print(x)
##################################
# użytkownik     system   upłynęło 
# 18.37       0.62      19.39 
##################################

Graph
