## THIS IS ONLY MAIN IDEA HOW OUR PACKAGE COULD WORK
## I WAS TESTING ADDING AND REMOVING LAYERS ON OBJECTS OF CLASS TRELLIS
## THAT ARE PRODUCED BY PCKG LATTICE.

## LAYERS ARE CREATED BY FUNCTIONS FROM PCKG latticeEXTRA

#Value

# a layer object is defined as a list of expression objects, 
# each of which may have a set of attributes. The result of 
# "adding" a layer to a trellis object (+.trellis) is the 
# updated trellis object.

# Really... ?


?layer
library(latticeExtra)


# turning default external box off
trellis.par.set("axis.line",list(col=NA,lty=1,lwd=1)) 

#You can restore the earlier behavior with: 
   
#trellis.par.set("axis.line",list(col="black",lty=1,lwd=1))


# Preparing an object of class trellis

Graph <- xyplot(0~0, xlab="", ylab="", type="l", 
              scales=list(draw=FALSE)) 
Graph
# Preparin coordinates of a turtle
coor <- c(0,0)
Graph + layer({panel.text(coor[1], coor[2], "-O-") })

# Graph is still a plot withouth a turtle
Graph

# new coordinates to move up to, generated by e.g. move_forward function
n_coor <- c(0.3,0.22)

## adding next line to a plot
Graph + layer(panel.xyplot(y = c(coor[2],n_coor[2]), x=c(coor[1],n_coor[1]),
                   type = "l", col="red"))
## updating our Graph
Graph <- Graph + layer(panel.xyplot(y = c(coor[2],n_coor[2]), x=c(coor[1],n_coor[1]),
                                       type = "l", col="red"))
## checking how does it look like
Graph

## adding turtle to a plot
Graph + layer(panel.text(x=n_coor[1], y=n_coor[2], "-O-"))


## viewing Graph withouth a turtle:
Graph

## after that, we need to substitue coordinates, so we can add a turtle
coor <- n_coor
coor


###########################################
###########################################
################# TEST ####################
###########################################
###########################################

coor <- c(0,0)
trellis.par.set("axis.line",list(col=NA,lty=1,lwd=1)) 
Graph <- xyplot(0~0, xlab="", ylab="", type="l", 
                scales=list(draw=FALSE),subscripts = TRUE) 
Graph + layer({panel.text(coor[1], coor[2], "-O-") })
n_coor <- as.data.frame(matrix(ncol=2,nrow=100))

n_coor[1,] <- round(runif(2)/10, digits=3) 


for (i in 2:100){   
   n_coor[i,] <- round(runif(2)/5, digits=3) #i suppose here isnt everything ok
   Graph <- Graph + layer(panel.lines(x=c(n_coor[1:i,1]),
                                       y=c(n_coor[1:i,2])))
   Graph
   Graph + layer(panel.text(x=n_coor[i,1], y=n_coor[i,2], "-O-"))

}


Graph + layer(panel.text(x=n_coor[i,1], y=n_coor[i,2], "-O-"))


testing <- function(){
   coor <- c(0,0)
   trellis.par.set("axis.line",list(col=NA,lty=1,lwd=1)) 
   Graph <- xyplot(0~0, xlab="", ylab="", type="l", 
                   scales=list(draw=FALSE),subscripts = TRUE) 
   Graph + layer({panel.text(coor[1], coor[2], "-O-") })
   n_coor <- as.data.frame(matrix(ncol=2,nrow=100))
   
   n_coor[1,] <- round(runif(2)/10, digits=3) 
   
   
   for (i in 2:100){   
      n_coor[i,] <- round(runif(2)/5, digits=3) #i suppose here isnt everything ok
      Graph <- Graph + layer(panel.lines(x=c(n_coor[1:i,1]),
                                         y=c(n_coor[1:i,2])))
      Graph
      Graph + layer(panel.text(x=n_coor[i,1], y=n_coor[i,2], "-O-"))
      
   }
}
require(microbenchmark)
microbenchmark(testing())

# https://stat.ethz.ch/R-manual/R-devel/library/lattice/html/update.trellis.html